# Generated by Django 5.1.3 on 2026-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_proveedor_alter_factura_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso_minimo',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Útil para detectar errores de digitación en el pesaje', max_digits=10, verbose_name='Peso mínimo por unidad (kg)'),
        ),
    ]
