# Generated by Django 5.1.3 on 2026-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_producto_peso_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('desactivado', 'Desactivado')], default='disponible', max_length=20, verbose_name='Estado del producto'),
        ),
    ]
