# Generated by Django 5.1.3 on 2026-02-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagovendedor',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Pago de Venta'), ('adelanto', 'Adelanto / Saldo a Favor')], default='pago', max_length=10),
        ),
    ]
