# Generated by Django 6.0.6 on 2026-07-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vendedor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
    ]
