# Generated by Django 5.1.3 on 2026-08-11 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ajusteinventario_cantidad_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='fecha_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
