# Generated by Django 6.0.6 on 2026-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_entradaproducto_fecha_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', help_text='Cancelado = el producto fue quitado del pedido y su stock/costo ya fue revertido', max_length=20, verbose_name='Estado de la línea'),
        ),
    ]
