# Generated by Django 6.0.6 on 2026-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_detallepedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_por_kilo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto a descontar del precio por kilo de cada linea de este pedido. Se aplica solo a pedidos especificos, no de forma global.', max_digits=10, verbose_name='Descuento por kilo'),
        ),
    ]
