# Generated by Django 5.1.3 on 2026-09-16 15:32

from django.db import migrations, models


def copiar_descuento_del_pedido_a_las_lineas(apps, schema_editor):
    """El descuento vivia en el pedido y ya estaba aplicado sobre precio_venta.

    Al bajarlo a la linea hay que dejar registrado cuanto se descuento en cada
    una, si no se pierde el precio de lista original (que se reconstruye como
    precio_venta + descuento_por_kilo al editar la linea).
    """
    DetallePedido = apps.get_model("core", "DetallePedido")
    Pedido = apps.get_model("core", "Pedido")
    for pedido in Pedido.objects.filter(descuento_por_kilo__gt=0).only("id", "descuento_por_kilo"):
        DetallePedido.objects.filter(pedido_id=pedido.id).update(
            descuento_por_kilo=pedido.descuento_por_kilo
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_pedido_descuento_por_kilo"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallepedido",
            name="descuento_por_kilo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto descontado del precio por kilo del producto SOLO en esta linea. precio_venta ya viene con el descuento aplicado, asi que el precio de lista usado al vender se recupera como precio_venta + descuento_por_kilo (no se lee de Producto, que pudo cambiar de precio despues).",
                max_digits=10,
                verbose_name="Descuento por kilo",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="descuento_por_kilo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor por defecto del descuento por kilo para las lineas que no traen uno propio. El descuento real vive en cada linea (DetallePedido.descuento_por_kilo): se aplica por producto, no al pedido completo.",
                max_digits=10,
                verbose_name="Descuento por kilo (por defecto)",
            ),
        ),
        migrations.RunPython(
            copiar_descuento_del_pedido_a_las_lineas,
            migrations.RunPython.noop,
        ),
    ]
